# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('33f35745631bcdee7f93f7492a7ed0be_MjIwMTYyMjAxMy0wNS0wNiAxNToxNjowNy44ODg5NTc')
  end)
end
